In [4]:
import torch
print(torch.__version__)
print(torch.cuda.is_available()) 
print(torch.backends.mps.is_available()) # gpu대신 mps사용 / mps확인
print(torch.backends.mps.is_built()) 

2.1.1
False
True
True


In [5]:
# Mps 사용 설정
import torch
device = torch.device("mps")

### 텐서

#### 텐서 생성

In [7]:
import torch

print(torch.tensor([1, 2, 3])) # 입력된 데이터를 복사해 텐서로 변환하는 함수 (의도하지 않은 자료형으로 변경될 수 있음) 자동으로 자료형 할당
print(torch.Tensor([[1, 2, 3], [4, 5, 6]])) # 텐서의 기본형 텐서 인스턴스를 생성하는 클래스 (인스턴스를 생성하기 때문에 비어 있는 경우 비어있는 텐서 생성) 권장
print(torch.LongTensor([1, 2, 3]))
print(torch.FloatTensor([1, 2, 3]))

tensor([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1, 2, 3])
tensor([1., 2., 3.])


#### 텐서 속성
- 형태 (shape): 텐서의 차원
- 자료형 (dtype) : 텐서에 할당된 데이터 형식
- 장치 (device) : gpu가속 여부

In [10]:
import torch
device = torch.device("mps") # mps디바이스 설정

tensor = torch.rand(1, 2).to(device) # 호출
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.2418, 0.6633]], device='mps:0')
torch.Size([1, 2])
torch.float32
mps:0


#### 차원 변환

In [11]:
import torch

tensor = torch.rand(1, 2)
print(tensor)
print(tensor.shape)

tensor = tensor.reshape(2, 1)
print(tensor)
print(tensor.shape)

tensor([[0.6068, 0.6250]])
torch.Size([1, 2])
tensor([[0.6068],
        [0.6250]])
torch.Size([2, 1])


#### 자료형 설정

In [12]:
import torch

tensor = torch.rand((3, 3), dtype=torch.float)
print(tensor)

tensor([[0.2317, 0.1166, 0.9567],
        [0.0297, 0.1065, 0.6254],
        [0.2282, 0.7065, 0.5028]])


#### 장치 설정

In [17]:
# 현재 M1사용 중 cuda x
import torch

device = "mps" if torch.backends.mps.is_available() else "cpu"
cpu = torch.FloatTensor([1, 2, 3])
mps = torch.FloatTensor([1, 2, 3]).to(device)
tensor = torch.rand((1, 1), device=device)
print(device)
print(cpu)
print(mps)
print(tensor)

mps
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='mps:0')
tensor([[0.3711]], device='mps:0')


#### 장치 변환
- cpu장치를 사용하는 텐서와 다른 장치를 사용하는 텐서는 상호 간 연산이 불가능

In [1]:
import torch
device = torch.device("mps")

cpu = torch.FloatTensor([1,2,3])
mps = cpu.to(device)
mps2cpu = mps.cpu()
cpu2mps = cpu.to(device)
print(cpu)
print(mps)
print(mps2cpu)
print(cpu2mps)

tensor([1., 2., 3.])
tensor([1., 2., 3.], device='mps:0')
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='mps:0')


#### 넘파이 배열의 텐서 변환
- 넘파이나 다른 라이브러리 데이터를 파이토치에 활용하려면 텐서 형식으로 변환

In [1]:
import torch
import numpy as np

ndarray = np.array([1, 2, 3], dtype=np.uint8)
print(torch.tensor(ndarray))
print(torch.Tensor(ndarray))
print(torch.from_numpy(ndarray))

tensor([1, 2, 3], dtype=torch.uint8)
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.uint8)


#### 텐서의 넘파이 배열 변환
- 추론된 결과를 후처리하거나 결괏값을 활용할 때 사용
- 추론/평가 단계에서는 gradient decent가 필요없기 때문에 (매개변수 변경 x, 주어진 입력에 대한 출력만 계산함)
    - 이로인해 연산량을 줄일 수 있음

In [2]:
import torch

tensor = torch.FloatTensor([1,2,3]).to(torch.device('mps')) # 텐서는 모든 연산은 추적해 기록 이 기록을 통해 뎍전파 등의 연산 진행
ndarray = tensor.detach().cpu().numpy() # detach(): 현재 연산 그래프에서 분리된 새로운 텐서 변환 / cpu(): 메모리 텐서를 cpu메모리로 이동 / numpy(): numpy배열로 변환
print(ndarray)
print(type(ndarray))

[1. 2. 3.]
<class 'numpy.ndarray'>
