#### 다중 선형 회귀

In [2]:
# 선언
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader

train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [5]:
# 데이터세트와 로이터로더

train_dataset = TensorDataset(train_x, train_y) # 텐서들을 입력으로 받아 데이터셋을 만듬
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

In [6]:
# 모델, 오차 함수, 최적화 함수 
model = nn.Linear(2,2, bias=True)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [18]:
# 데이터로더 적용
for epoch in range(20000):
    cost = 0.0 # 에포크마다 오차를 다시 계산하기 위해 초기화

    for batch in train_dataloader:
        x, y = batch # 배치 2만큼의 train_x와 train_y의 값
        output = model(x)

        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader) # 오차 평균값 계산

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")
        

Epoch : 1000, Model : [Parameter containing:
tensor([[0.4408, 0.2940],
        [0.3257, 0.7776]], requires_grad=True), Parameter containing:
tensor([-0.4001,  0.2484], requires_grad=True)], Cost : 0.113
Epoch : 2000, Model : [Parameter containing:
tensor([[0.6083, 0.2076],
        [0.5251, 0.6747]], requires_grad=True), Parameter containing:
tensor([-0.6541, -0.0539], requires_grad=True)], Cost : 0.029
Epoch : 3000, Model : [Parameter containing:
tensor([[0.6936, 0.1636],
        [0.6267, 0.6223]], requires_grad=True), Parameter containing:
tensor([-0.7834, -0.2079], requires_grad=True)], Cost : 0.008
Epoch : 4000, Model : [Parameter containing:
tensor([[0.7371, 0.1411],
        [0.6784, 0.5956]], requires_grad=True), Parameter containing:
tensor([-0.8493, -0.2863], requires_grad=True)], Cost : 0.002
Epoch : 5000, Model : [Parameter containing:
tensor([[0.7592, 0.1297],
        [0.7048, 0.5820]], requires_grad=True), Parameter containing:
tensor([-0.8829, -0.3263], requires_grad=True)]

#### 편향 제거

In [19]:
model = nn.Linear(2, 2, bias=False)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [21]:
for epoch in range(20000):
    cost = 0.0

    for batch in train_dataloader:
        x, y = batch
        output = model(x)

        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")


Epoch : 1000, Model : [Parameter containing:
tensor([[ 1.6860, -0.7887],
        [ 1.0894,  0.2086]], requires_grad=True)], Cost : 0.000
Epoch : 2000, Model : [Parameter containing:
tensor([[ 1.6889, -0.7910],
        [ 1.0916,  0.2068]], requires_grad=True)], Cost : 0.000
Epoch : 3000, Model : [Parameter containing:
tensor([[ 1.6912, -0.7929],
        [ 1.0933,  0.2054]], requires_grad=True)], Cost : 0.000
Epoch : 4000, Model : [Parameter containing:
tensor([[ 1.6930, -0.7943],
        [ 1.0947,  0.2043]], requires_grad=True)], Cost : 0.000
Epoch : 5000, Model : [Parameter containing:
tensor([[ 1.6944, -0.7955],
        [ 1.0958,  0.2034]], requires_grad=True)], Cost : 0.000
Epoch : 6000, Model : [Parameter containing:
tensor([[ 1.6956, -0.7964],
        [ 1.0966,  0.2027]], requires_grad=True)], Cost : 0.000
Epoch : 7000, Model : [Parameter containing:
tensor([[ 1.6965, -0.7971],
        [ 1.0973,  0.2022]], requires_grad=True)], Cost : 0.000
Epoch : 8000, Model : [Parameter containi