In [2]:
# 단층 퍼셉트론 구조

import torch
import pandas as pd
from torch import nn
from torch import optim
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, file_path):
        df = pd.read_csv(file_path)
        self.x1 = df.iloc[:, 0].values
        self.x2 = df.iloc[:, 1].values
        self.y = df.iloc[:, 2].values
        self.length = len(df)

    def __getitem__(self, index):
        x = torch.FloatTensor([self.x1[index], self.x2[index]])
        y = torch.FloatTensor([self.y[index]])
        return x, y
    
    def __len__(self):
        return self.length

class CustomModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.layer = nn.Sequential(
            nn.Linear(2,1),
            nn.Sigmoid()
        )
    
    def forward(self, x):
        x = self.layer(x)
        return x

train_dataset = CustomDataset('./dataset/perceptron.csv')
train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True, drop_last=True)

device = torch.device('mps')
model = CustomModel().to(device)
criterion = nn.BCELoss().to(device)
optimizer = optim.SGD(model.parameters(), lr = 0.01)

for epoch in range(10000):
    cost = 0.0

    for x, y in train_dataloader:
        x = x.to(device)
        y = y.to(device)

        output = model(x)

        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss
    
    cost = cost / len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f'epoch: {epoch+1:4d}, Cost : {cost:.3f}')

# 모델 평가
with torch.no_grad():
    model.eval()
    inputs = torch.FloatTensor([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ]).to(device)
    outputs = model(inputs)

    print("---------------------------")
    print(outputs)
    print(outputs <= 0.5)

    # 단층 퍼셉트론 구조로는 XOR 문제를 해결하기 힘듬

/var/folders/_k/k4vg8yqs5bd1kvyznqhzdt3r0000gn/T/ipykernel_50182/2892780961.py:18: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  x = torch.FloatTensor([self.x1[index], self.x2[index]])
/var/folders/_k/k4vg8yqs5bd1kvyznqhzdt3r0000gn/T/ipykernel_50182/2892780961.py:19: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  y = torch.FloatTensor([self.y[index]])


epoch: 1000, Cost : 0.691
epoch: 2000, Cost : 0.692
epoch: 3000, Cost : 0.692
epoch: 4000, Cost : 0.692
epoch: 5000, Cost : 0.692
epoch: 6000, Cost : 0.692
epoch: 7000, Cost : 0.693
epoch: 8000, Cost : 0.692
epoch: 9000, Cost : 0.691
epoch: 10000, Cost : 0.692
---------------------------
tensor([[0.4675],
        [0.4997],
        [0.5038],
        [0.5360]], device='mps:0')
tensor([[ True],
        [ True],
        [False],
        [False]], device='mps:0')


- DeprecationWarning
- /var/folders/_k/k4vg8yqs5bd1kvyznqhzdt3r0000gn/T/ipykernel_50182/2892780961.py:18: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  x = torch.FloatTensor([self.x1[index], self.x2[index]])
- /var/folders/_k/k4vg8yqs5bd1kvyznqhzdt3r0000gn/T/ipykernel_50182/2892780961.py:19: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  y = torch.FloatTensor([self.y[index]])

- index가 np.bool 타입으로 되어있을 경우 발생 -> 향후 버전에서 오류 위험이 있음

In [4]:
# 다층 퍼셉트론 구조

class CustomModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.layer1 = nn.Sequential(
            nn.Linear(2, 2),
            nn.Sigmoid()
        )
        self.layer2 = nn.Sequential(
            nn.Linear(2, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        return x
    

train_dataset = CustomDataset('./dataset/perceptron.csv')
train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True, drop_last=True)

device = torch.device('mps')
model = CustomModel().to(device)
criterion = nn.BCELoss().to(device)
optimizer = optim.SGD(model.parameters(), lr = 0.01)

for epoch in range(10000):
    cost = 0.0

    for x, y in train_dataloader:
        x = x.to(device)
        y = y.to(device)

        output = model(x)

        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss
    
    cost = cost / len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f'epoch: {epoch+1:4d}, Cost : {cost:.3f}')

# 모델 평가
with torch.no_grad():
    model.eval()
    inputs = torch.FloatTensor([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ]).to(device)
    outputs = model(inputs)

    print("---------------------------")
    print(outputs)
    print(outputs <= 0.5)

    # 다층 퍼셉트론 구조로 비용이 감소하는 것을 확인 

/var/folders/_k/k4vg8yqs5bd1kvyznqhzdt3r0000gn/T/ipykernel_50182/2892780961.py:18: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  x = torch.FloatTensor([self.x1[index], self.x2[index]])
/var/folders/_k/k4vg8yqs5bd1kvyznqhzdt3r0000gn/T/ipykernel_50182/2892780961.py:19: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  y = torch.FloatTensor([self.y[index]])


epoch: 1000, Cost : 0.685
epoch: 2000, Cost : 0.567
epoch: 3000, Cost : 0.416
epoch: 4000, Cost : 0.102
epoch: 5000, Cost : 0.043
epoch: 6000, Cost : 0.027
epoch: 7000, Cost : 0.019
epoch: 8000, Cost : 0.015
epoch: 9000, Cost : 0.012
epoch: 10000, Cost : 0.010
---------------------------
tensor([[0.0112],
        [0.9908],
        [0.9908],
        [0.0108]], device='mps:0')
tensor([[ True],
        [False],
        [False],
        [ True]], device='mps:0')
