In [2]:
# numpy 숫자형, 문자형, 논리형 벡터 생성 예제

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array(['apple', 'banana', 'orange'])
c = np.array([True, False, True, True])

print('Numeric Vector:', a)
print('String Vector:', b)
print('Boolean Vector:', c)

Numeric Vector: [1 2 3 4 5]
String Vector: ['apple' 'banana' 'orange']
Boolean Vector: [ True False  True  True]


In [9]:
# 빈 배열 생성
x = np.empty(3)
print('빈 벡터 생성', x) # 메모리의 임의의 값을 가지며 시스템에 따라 다르다

# 배열 채우기
x[0] = 3
x[1] = 5
x[2] = 3
print("채워진 벡터:", x)

빈 벡터 생성 [3. 5. 3.]
채워진 벡터: [3. 5. 3.]


### 배열을 생성하면서 채우는 방법
- np.array() : 함수로 직접 입력
- np.arange() : 함수로 사용하여 일정한 간격의 숫자 배열 생성
- np.linspace() : 함수를 사용하여 지정된 범위를 균일하게 나눈 숫자 배열 생성

In [ ]:
# np.arange([start, ], stop, [step,], dtype=None) 함수

import numpy as np

arr1 = np.arange(10)
print('0부터 9까지 배열', arr1)

arr2 = np.arange(0, 2, 0.5)
print('0부터 2미만 0.5 간격 출력', arr2)

0부터 9까지 배열 [0 1 2 3 4 5 6 7 8 9]
0부터 2미만 0.5 간격 출력 [0.  0.5 1.  1.5]


### np.linspace()
- 시작점과 종료점 사이의 균일한 간격의 숫자 배열 생성
- np.linspace(start, stop, num=50, endpoint=True, restep=False, dtype=None)
    - start: 시퀀스의 시작값
    - stop: 시퀀스의 종료값, endpoint=True라면 해당 값이 배열에 포함
    - endpoint: True인 경우 stop이 마지막 샘플로 포함
    - restep: True인 경우 결과와 함께 샘플 간의 간격도 반환
    - dtype: 배열의 데이터 타입을 지정

In [20]:
# np.linspace 함수 

linear_space1 = np.linspace(0, 1, 5)
print("0부터 1까지 5개 값", linear_space1)

# endpoint= false인 경우
linear_space1 = np.linspace(0, 1, 5, endpoint=False)
print("0부터 1까지 5개 값, end point 제외", linear_space1)

0부터 1까지 5개 값 [0.   0.25 0.5  0.75 1.  ]
0부터 1까지 5개 값, end point 제외 [0.  0.2 0.4 0.6 0.8]


### np.repeat()
- 반복되는 요소를 배열로 생성
- np.repeat(a, repeats, axis=None)
    - a: 반복할 입력 배열
    - repeats: 각 요소를 반복할 횟수
    - axis: 반복을 적용할 축을 지정, 기본값 none, 배열을 평평하게 만든 후 반복

In [ ]:
# 단일 값 반복

repeated_vals = np.repeat(8, 4)

print("8을 4번 반복", repeated_vals)

8을 4번 반복 [8 8 8 8]


In [23]:
# 배열 반복

repeated_array = np.repeat([1,2,4], 2)
print('배열 [1,2,4] 두번 반복', repeated_array)

배열 [1,2,4] 두번 반복 [1 1 2 2 4 4]


In [25]:
# 각 요소를 반복

repeated_each = np.repeat([1,2,4], repeats=[1,2,3])
print('각 배열의 요소 반복', repeated_each)

각 배열의 요소 반복 [1 2 2 4 4 4]


### np.tile()
- 벡터 전체 반복
- np.tile(a, reps)
    - a: 반복할 입력 배열
    - reps: 반복할 횟수

In [26]:
repeated_whole = np.tile([1,2,4], 2)
print('전체 배열을 두 번 반복', repeated_whole)

전체 배열을 두 번 반복 [1 2 4 1 2 4]


### 벡터의 길이

In [ ]:
# len으로 길이 구하기

import numpy as np
a = np.array([1,2,3,4,5])
len(a)

5

In [29]:
# shape 속성으로 크기 구하기
a = np.array([1,2,3,4,5])
a.shape

(5,)

In [30]:
# size 속성으로 전체 요소 수 구하기 (배열의 모든 요소의 개수)

a = np.array([1,2,3,4,5])
a.size



5

### numpy 벡터 슬라이싱(slicing)


In [32]:
# 벡터 슬라이싱 예제

import numpy as np

np.random.seed(42)
a = np.random.randint(1, 21, 10)
print(a)
print(a[1])

[ 7 20 15 11  8  7 19 11 11  4]
20


In [ ]:
# 3번째 값부터 다섯 번째 값 추출
print(a[2:5])

[15 11  8]


In [ ]:
# 첫번째 세번째, 다섯 번째 값 추출
print(a[[0,2,4]])
# a 배열 중 두번 째 값 제외하고 추출
print(np.delete(a, 1))

[ 7 15  8]
[ 7 15 11  8  7 19 11 11  4]


In [ ]:
# 인덱싱 중복 선택
print(a)
print(a[[1,1,3,2]])

[ 7 20 15 11  8  7 19 11 11  4]
[20 20 11 15]


In [ ]:
# a 요소 중 3보다 큰 요소 추출 b 할당
b = a[a > 3]
print(b)

[ 7 20 15 11  8  7 19 11 11  4]


### 논리 연산자와 조건문
- 대괄호 안에 연산자 조합하여 원하는 값을 추출

In [ ]:
b = a[( a > 2 ) & ( a < 9 )]
print(b)

[7 8 7 4]


### np.where()
- 조건에 만족하는 원소의 위치를 반환할 수 있음

In [54]:
a = np.array([1,5,7,8,10])

result = a < 7
result

array([ True,  True, False, False, False])

In [56]:
result = np.where(a < 7)
result

(array([0, 1]),)

## numpy 벡터 활용

In [58]:
import numpy as np
a = np.array([1,2,3,4,5])

sum_a = np.sum(a) # 총합
mean_a = np.mean(a) # 평균
median_a = np.median(a) # 중앙값
std_a = np.std(a, ddof=1) # 표준편차

sum_a, mean_a, median_a, std_a

(15, 3.0, 3.0, 1.5811388300841898)

In [ ]:
# 데이터 정의: x np.nan (정의되지 않은 값이나 잘못된 값)

a = np.array([20, np.nan, 13, 24, 309])
a

array([ 20.,  nan,  13.,  24., 309.])

In [ ]:
# nan은 다른 어떤 수와 계산해도 그 결과 nan
np.mean(a)

nan

In [61]:
# nan 무시 옵션
np.nanmean(a)

91.5

In [62]:
# 값이 없는 상태: none (값이 없음을 나타내는 특수한 상수)

import numpy as np

value = np.nan
if np.isnan(value):
    print("값이 NaN입니다.")

값이 NaN입니다.


In [64]:
# nan은 수치연산이 가능하나 결과는 nan
value + 1

nan

In [65]:
my_variable = None
if my_variable is None:
    print('변수에 값이 없습니다.')

변수에 값이 없습니다.


In [66]:
# 수치연산 불가능
None + 1

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [67]:
# 빈 칸 제거 방법 ()

a = np.array([20, np.nan, 13, 24, 309])

a_filtered = a[~np.isnan(a)]
a_filtered

array([ 20.,  13.,  24., 309.])

In [ ]:
# 벡터 합치기

str_vec = np.array(["사과", "배", "수박", "참외"])
str_vec
# U2는 최대 2 글자의 유니코드 문자열 의미

array(['사과', '배', '수박', '참외'], dtype='<U2')

In [69]:
mix_vec = np.array(['사과', 12, '수박', '참외'], dtype=str)
mix_vec

array(['사과', '12', '수박', '참외'], dtype='<U2')

### np.concatenate()

In [71]:
combined_vec = np.concatenate((str_vec, mix_vec))
combined_vec

array(['사과', '배', '수박', '참외', '사과', '12', '수박', '참외'], dtype='<U2')

### np.column_stack(), np.row_stack()
- column_stack(): 벡터들을 세로로 붙여준다
- row_stack(): 벡터들을 가로로 쌓아준다

In [76]:
col_stacked = np.column_stack((np.arange(1, 5), np.arange(12, 16)))
col_stacked

array([[ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15]])

### np.resize()
- 벡터 길이 조정

In [ ]:
# 서로 길이가 다르기 때문에 오류가 발생
uneven_stacked = np.column_stack((np.arange(1,5), np.arange(12, 18)))

# 길이가 다른 경우 쌓을 수 없는 것 확인 -> np.resize 함수를 사용하여 길이를 맞춰주고 값을 앞에서부터 채워줌

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 6

In [ ]:
vec1 = np.arange(1,5)
vec2 = np.arange(12, 18)
vec1 = np.resize(vec1, len(vec2))
vec1 # 앞에 값부터 채워주는 것을 확인할 수 있음

array([1, 2, 3, 4, 1, 2])

In [ ]:
# 길이를 맞춰준 후 column_stack 함수 실행
uneven_stacked = np.column_stack((vec1, vec2))
uneven_stacked

array([[ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15],
       [ 1, 16],
       [ 2, 17]])

In [ ]:
# 1
a = np.array([1,2,3,4,5])
a+5

array([ 6,  7,  8,  9, 10])

In [ ]:
# 2
a = np.array([12,21,35,48,5])
a[[0,2,4]]
# a[[::2]]

array([12, 35,  5])

In [86]:
# 3
a = np.array([1,22,93,64,54])
np.max(a)

93

In [87]:
# 4
a = np.array([1, 2, 3, 2, 4, 5, 4, 6])
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [92]:
# 5
a = np.array([21, 31, 58])
b = np.array([24, 44, 67])
c = np.empty([a.size + b.size])
c[0::2] = a
c[1::2] = b
print(c)

[21. 24. 31. 44. 58. 67.]


In [ ]:
# 6
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9])
c = a[:-1] + b
print(c)

[ 7  9 11 13]
