In [2]:
import numpy as np

a = np.random.randn(5)

In [3]:
print(a)

[-1.62332382  0.85881763 -1.3810795   1.20207209 -1.4176475 ]


In [4]:
print(a.shape)

(5,)


In [6]:
print(a.T) # Rank-1 array로 행도 열도 아닌 벡터며 직관적이지 않음

[-1.62332382  0.85881763 -1.3810795   1.20207209 -1.4176475 ]


In [8]:
print(a.shape)

(5,)


In [7]:
print(a.T) # Rank-1 array는 전치를 하여도 a와 동일하게 보임

[-1.62332382  0.85881763 -1.3810795   1.20207209 -1.4176475 ]


In [9]:
print(np.dot(a, a.T)) # Rank-1 array를 내적할 경우 하나의 스칼라

8.734830284836365


In [ ]:
# Rank-1 array를 사용하지 않는 것 추천

In [10]:
a = np.random.randn(5,1)
print(a)

[[-1.02105189]
 [-0.73865529]
 [-0.13382552]
 [ 0.31500643]
 [-0.9320681 ]]


In [11]:
print(a.T)

[[-1.02105189 -0.73865529 -0.13382552  0.31500643 -0.9320681 ]]


In [12]:
print(np.dot(a, a.T))

[[ 1.04254696  0.75420538  0.1366428  -0.32163791  0.95168989]
 [ 0.75420538  0.54561163  0.09885093 -0.23268116  0.68847703]
 [ 0.1366428   0.09885093  0.01790927 -0.0421559   0.1247345 ]
 [-0.32163791 -0.23268116 -0.0421559   0.09922905 -0.29360744]
 [ 0.95168989  0.68847703  0.1247345  -0.29360744  0.86875094]]


In [13]:
# 형태 변형 확인하기

assert(a.shape == (5,1))

In [15]:
a

array([[-1.02105189],
       [-0.73865529],
       [-0.13382552],
       [ 0.31500643],
       [-0.9320681 ]])